version: 2
builds:
- id: "platform-operator"
  dir: platform-operator
  main: ./cmd
  binary: ./bin/platform-operator-manager
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: darwin
    goarch: ppc64le
  env:
  - CGO_ENABLED=0
archives:
- ids: [platform-operator]
kos:
  - id: "platform-operator-ko"
    repositories:
    - ghcr.io/kagenti/kagenti-operator/platform-operator
    working_dir: platform-operator
    main: ./cmd
    build: platform-operator
    tags:
      - '{{.Version}}'
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
    env:
      - CGO_ENABLED=0
release:
  draft: false
  prerelease: auto
  mode: keep-existing
