---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-agent-kagenti-dev-v1alpha1-agentbuild
  failurePolicy: Fail
  name: magentbuild.kb.io
  rules:
  - apiGroups:
    - agent.kagenti.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - agentbuilds
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-agent-kagenti-dev-v1alpha1-agentbuild
  failurePolicy: Fail
  name: vagentbuild.kb.io
  rules:
  - apiGroups:
    - agent.kagenti.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - agentbuilds
  sideEffects: None
