apiVersion: v1
kind: Namespace
metadata:
  name: kagenti
---
apiVersion: kagenti.operator.dev/v1alpha1
kind: Component
metadata:
  name: research-agent
  namespace: kagenti

spec:
  description: "A research agent for information gathering"
  suspend: false
  agent:
    # Optional build specification for building from source
    build:
      mode: dev
      pipeline:
        parameters:
          - name: github-token-secret
            value: "github-credentials"
          - name: repo-url
            value: "github.com/kagenti/agent-examples.git"
          - name: revision
            value: "main"
          - name: subfolder-path
            value: "acp/acp_ollama_researcher"
          - name: image
            value: "registry.cr-system.svc.cluster.local:5000/beai-research-agent:latest"
      cleanupAfterBuild: true

  deployer:
    name: "my-agent-deployment"
    namespace: kagenti
    deployAfterBuild: true
    kubernetes:
      imageSpec:
        image: "beai-research-agent"
        imageTag: "latest"
        imageRegistry: "registry.cr-system.svc.cluster.local:5000"
        imagePullPolicy: "IfNotPresent"
      containerPorts:
        - name: "http"
          containerPort: 8090
          protocol: "TCP"
      servicePorts:
        - name: "http"
          port: 8008
          targetPort: 8090
          protocol: "TCP"
      resources:
        limits:
          cpu: "1"
          memory: "2Gi"
        requests:
          cpu: "500m"
          memory: "1Gi"
      serviceType: "ClusterIP"

    env:
      - name: HOST
        value: "0.0.0.0"
      - name: LLM_API_BASE
        value: "http://host.docker.internal:11434/v1"
      - name: LLM_API_KEY
        value: "dummy"
      - name: LLM_MODEL
        value: "llama3.2:3b-instruct-fp16"
