apiVersion: agent.kagenti.dev/v1alpha1
kind: Agent
metadata:
  name: weather-agent
  namespace: kagenti
  labels:
    app: weather-service

  annotations:
    description: "Weather data processing agent deployed from source"
spec:
  description: "Agent that processes weather data - built from source"

  replicas: 1

  # Reference AgentBuild instead of direct image
  imageSource:
    buildRef:
      name: weather-agent-build

  # Define service ports to expose
  servicePorts:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: 9090

  # Complete pod template specification
  podTemplateSpec:
    spec:

      containers:
      - name: agent  # use fixed name "agent" for the main container
        image: <will be replaced with image from AgentBuild>
        imagePullPolicy: IfNotPresent

        # Resource limits and requests
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        # Environment variables
        env:
        - name: PORT
          value: "8000"
        - name: HOST
          value: 0.0.0.0
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector.kagenti-system.svc.cluster.local:8335
        - name: KEYCLOAK_URL
          value: http://keycloak.keycloak.svc.cluster.local:8080
        - name: UV_CACHE_DIR
          value: /app/.cache/uv
        - name: LLM_API_BASE
          value: http://host.docker.internal:11434/v1
        - name: LLM_API_KEY
          value: dummy
        - name: LLM_MODEL
          value: llama3.2:3b-instruct-fp16
        - name: MCP_URL
          value: http://weather-tool:8000/mcp
        - name: GITHUB_SECRET_NAME
          value: github-token-secret
        - name: CLIENT_NAME
          value: kagenti/weather-service
        - name: CLIENT_ID
          value: spiffe://localtest.me/sa/weather-service
        - name: NAMESPACE
          value: kagenti

        # Ports
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP

        # Volume mounts
        volumeMounts:
        - name: cache
          mountPath: /app/.cache
        - mountPath: /.marvin
          name: marvin
        - mountPath: /shared
          name: shared-data

      # Volumes
      volumes:
      - emptyDir: {}
        name: cache
      - emptyDir: {}
        name: marvin
      - emptyDir: {}
        name: shared-data
