apiVersion: agent.kagenti.dev/v1alpha1
kind: AgentBuild
metadata:
  name: weather-agent-build
  namespace: kagenti
  labels:
    app: weather-service
  annotations:
    description: "Build configuration for weather agent from source"
spec:
  source:
    sourceRepository: "github.com/kagenti/agent-examples.git"
    sourceRevision: "main"
    sourceSubfolder: "a2a/weather_service"
<<<<<<< HEAD
<<<<<<< HEAD
    sourceCredentials:
      name: github-token-secret

=======
    sourceCredentials: 
      name: github-token-secret
  
>>>>>>> 0230991 (controller implementation of the agentbuild_controller)
=======
    sourceCredentials:
      name: github-token-secret

>>>>>>> 2b17fd5 (adds implementation of agentbuild api)
  buildOutput:
    image: "weather-service"
    imageTag: "v0.0.1"
    imageRegistry: "registry.cr-system.svc.cluster.local:5000"
    imageRepoCredentials:
      name: ghcr-secret
<<<<<<< HEAD
<<<<<<< HEAD

=======
  
>>>>>>> 0230991 (controller implementation of the agentbuild_controller)
=======

>>>>>>> 2b17fd5 (adds implementation of agentbuild api)
  pipeline:
    namespace: kagenti-system
    steps:
      - name: git-clone
        configMap: github-clone-step
      - name: folder-check
        configMap: check-subfolder-step
      - name: kaniko-build
        configMap: kaniko-docker-build-step
<<<<<<< HEAD
<<<<<<< HEAD

  # Cleanup after successful build
  cleanupAfterBuild: true

  # Use dev mode pipeline
  mode: dev
=======
  
=======

>>>>>>> 2b17fd5 (adds implementation of agentbuild api)
  # Cleanup after successful build
  cleanupAfterBuild: true

  # Use dev mode pipeline
  mode: dev
<<<<<<< HEAD
>>>>>>> 0230991 (controller implementation of the agentbuild_controller)
=======
>>>>>>> 2b17fd5 (adds implementation of agentbuild api)
