apiVersion: agent.kagenti.dev/v1alpha1
kind: AgentBuild
metadata:
  name: weather-agent-build
  namespace: kagenti
spec:
  source:
    sourceRepository: "github.com/kagenti/agent-examples.git"
    sourceRevision: "main"
    sourceSubfolder: "a2a/weather_service"
    sourceCredentials:
      name: github-token-secret

  pipeline:
    namespace: kagenti-system
    parameters:
    - name: SOURCE_REPO_SECRET
      value: github-token-secret

  buildOutput:
    image: "weather-service"
    imageTag: "v0.0.1"
    imageRegistry: "registry.cr-system.svc.cluster.local:5000"
    imageRepoCredentials:
      name: ghcr-secret

---
apiVersion: agent.kagenti.dev/v1alpha1
kind: Agent
metadata:
  name: weather-agent
  namespace: kagenti
  labels:
    app: weather-service

  annotations:
    description: "Weather data processing agent"
spec:
  description: "Agent that processes weather data"

  replicas: 1

  # Use existing container image
  imageSource:
    buildRef:
      name: weather-agent-build

  # Complete pod template specification
  podTemplateSpec:
    spec:

      containers:
      - name: agent # use fixed name "agent" for the main container
        image:  <will be replaced with imageSource.image above>

        # Environment variables
        env:
        - name: PORT
          value: "8000"
        - name: HOST
          value: 0.0.0.0
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector.kagenti-system.svc.cluster.local:8335
        - name: KEYCLOAK_URL
          value: http://keycloak.keycloak.svc.cluster.local:8080
        - name: UV_CACHE_DIR
          value: /app/.cache/uv
        - name: LLM_API_BASE
          value: http://host.docker.internal:11434/v1
        - name: LLM_API_KEY
          value: dummy
        - name: LLM_MODEL
          value: llama3.2:3b-instruct-fp16
        - name: MCP_URL
          value: http://weather-tool:8000/mcp
        - name: GITHUB_SECRET_NAME
          value: github-token-secret
        - name: CLIENT_NAME
          value: kagenti/weather-service
        - name: CLIENT_ID
          value: spiffe://localtest.me/sa/weather-service
        - name: NAMESPACE
          value: kagenti
