# This rule is not used by the project kagenti-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over agent.kagenti.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kagenti-operator
    app.kubernetes.io/managed-by: kustomize
  name: agent-admin-role
rules:
- apiGroups:
  - agent.kagenti.dev
  resources:
  - agents
  verbs:
  - '*'
- apiGroups:
  - agent.kagenti.dev
  resources:
  - kagents/status
  verbs:
  - get
