# This rule is not used by the project kagenti-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to agent.kagenti.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kagenti-operator
    app.kubernetes.io/managed-by: kustomize
  name: kagentiagentbuild-viewer-role
rules:
- apiGroups:
  - agent.kagenti.dev
  resources:
  - kagentiagentbuilds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - agent.kagenti.dev
  resources:
  - kagentiagentbuilds/status
  verbs:
  - get
