apiVersion: v1
kind: ConfigMap
metadata:
  name: kaniko-docker-build-step-local
  namespace: "{{ .Release.Namespace }}"
  labels:
    kagenti.operator.dev/tekton: step 
data:
  task-spec.yaml: |
    params:
      - name: DOCKERFILE
        type: string
        description: Path to the Dockerfile relative to context
        default: "Dockerfile"
      - name: image
        type: string
        description: Destination image reference
      - name: SKIP_TLS_VERIFY
        type: string
        description: Skip TLS verification when pushing to registry
        default: "false"
      - name: subfolder-path
        type: string
        description: Path to the subfolder to use as build context
    steps:
      - name: docker-build
        image: quay.io/strimzi/kaniko-executor:0.48.0
        args:
          - --dockerfile=$(params.DOCKERFILE)
          - --context=$(workspaces.source.path)/$(params.subfolder-path)
          - --destination=$(params.image)
          - --skip-tls-verify=$(params.SKIP_TLS_VERIFY)
          - --verbosity=trace
        # No volumeMounts or DOCKER_CONFIG for local registry
    # No volumes section for local registry
    workspaces:
      - name: source
