apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-template-dev-local
  namespace: kagenti-system
  labels:
    app.kubernetes.io/component: pipeline-template
    app.kubernetes.io/name: component-operator
    component.kagenti.ai/mode: dev-local
data:
  template.json: |
    {
      "name": "Development Pipeline (Local Registry)",
      "namespace": "kagenti-system",     
      "description": "Basic pipeline for development builds with local registry",
      "requiredParameters": [
        "repo-url",
        "revision",
        "subfolder-path",
        "image"
      ],
      "steps": [
        {
          "name": "github-clone",
          "configMap": "github-clone-step",
          "enabled": true,
          "description": "Clone source code from GitHub repository",
          "requiredParameters": ["repo-url"]
        },
        {
          "name": "folder-verification",
          "configMap": "check-subfolder-step",
          "enabled": true,
          "description": "Verify that the specified subfolder exists",
          "requiredParameters": ["subfolder-path"]
        },
        {
          "name": "kaniko-build",
          "configMap": "kaniko-docker-build-step-local",
          "enabled": true,
          "description": "Build container image using Kaniko (no registry authentication)",
          "requiredParameters": ["image"]
        }
      ],
      "globalParameters": [
        {
          "name": "pipeline-timeout",
          "value": "20m",
          "description": "Overall pipeline timeout"
        }
      ]
    }
